name: TOC Bump

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Update TOC Interface version
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: retail

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore: Update Interface version"
          commit-message: "Update Interface version"
          branch: toc-bump
          delete-branch: true
